In [1]:
import math

import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn import metrics

import statsmodels.api as sm

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
df = pd.read_csv('../data/colleges.csv')
df['University'] = 0

for i in range(0, len(df.index)):
    if df.iloc[i]['Type'] == 'University':
        df.loc[i,'University'] = 1

df

,School,Type,MedianSAT,AcceptanceRate,ExpendituresPerStudent,Top10PercentHS,GraduationPercent,University
0,Amherst,Lib Arts,1315,0.22,26636,85,93,0
1,Barnard,Lib Arts,1220,0.53,17653,69,80,0
2,Bates,Lib Arts,1240,0.36,17554,58,88,0
3,Berkeley,University,1176,0.37,23665,95,68,1
4,Bowdoin,Lib Arts,1300,0.24,25703,78,90,0
5,Brown,University,1281,0.24,24201,80,90,1
6,Bryn Mawr,Lib Arts,1255,0.56,18847,70,84,0
7,Cal Tech,University,1400,0.31,102262,98,75,1
8,Carleton,Lib Arts,1300,0.40,15904,75,80,0
9,Carnegie Mellon,University,1225,0.64,33607,52,77,1
10,Claremont McKenna,Lib Arts,1260,0.36,20377,68,74,0
11,Colby,Lib Arts,1200,0.46,18872,52,84,0
12,Colgate,Lib Arts,1258,0.38,17520,61,85,0
13,Columbia,University,1268,0.29,45879,78,90,1
14,Cornell,University,1280,0.30,37137,85,83,1
15,Davisdson,Lib Arts,1230,0.36,17721,77,89,0
16,Duke,University,1310,0.25,39504,91,91,1
17,Georgetown,University,1278,0.24,23115,79,89,1
18,Grinnell,Lib Arts,1244,0.67,22301,65,73,0
19,Hamilton,Lib Arts,1215,0.38,20722,51,85,0
20,Harvard,University,1370,0.18,46918,90,90,1
21,Haverford,Lib Arts,1285,0.35,19418,71,87,0
22,Johns Hopkins,University,1290,0.48,45460,69,86,1
23,Middlebury,Lib Arts,1255,0.25,24718,65,92,0
24,MIT,University,1357,0.30,56766,95,86,1
25,Mount Holyoke,Lib Arts,1200,0.61,23358,47,83,0
26,Northwestern,University,1230,0.47,28851,77,82,1
27,Oberlin,Lib Arts,1247,0.54,23591,64,77,0
28,Occidental,Lib Arts,1170,0.49,20192,54,72,0
29,Pomona,Lib Arts,1320,0.33,26668,79,80,0
30,Princeton,University,1340,0.17,48123,89,93,1
31,Rice,University,1327,0.24,26730,85,88,1
32,Smith,Lib Arts,1195,0.57,25271,65,87,0
33,Stanford,University,1370,0.18,61921,92,88,1
34,Swarthnore,Lib Arts,1310,0.24,27487,78,88,0
35,U Michigan,University,1195,0.60,21853,71,77,1
36,U of Chicago,University,1300,0.45,38937,74,73,1
37,U of Rochester,University,1155,0.56,38597,52,73,1
38,U Pennsylvania,University,1280,0.41,30882,87,86,1
39,U Va,University,1218,0.37,19365,77,88,1
40,UCLA,University,1142,0.43,26859,96,61,1
41,UNC,University,1109,0.32,19684,82,73,1
42,Vassar,Lib Arts,1287,0.43,20179,53,84,0
43,Washington U (MO),University,1225,0.54,39883,71,76,1
44,Washinton and Lee,Lib Arts,1234,0.29,17998,61,78,0
45,Wellesley,Lib Arts,1250,0.49,27879,76,86,0
46,Wesleyan (CT),Lib Arts,1290,0.35,19948,73,91,0
47,Williams,Lib Arts,1336,0.28,23772,86,93,0
48,Yale,University,1350,0.19,52468,90,93,1

In [4]:
df = df.drop('School', axis=1)
df = df.drop('Type', axis=1)
df

,MedianSAT,AcceptanceRate,ExpendituresPerStudent,Top10PercentHS,GraduationPercent,University
0,1315,0.22,26636,85,93,0
1,1220,0.53,17653,69,80,0
2,1240,0.36,17554,58,88,0
3,1176,0.37,23665,95,68,1
4,1300,0.24,25703,78,90,0
5,1281,0.24,24201,80,90,1
6,1255,0.56,18847,70,84,0
7,1400,0.31,102262,98,75,1
8,1300,0.40,15904,75,80,0
9,1225,0.64,33607,52,77,1
10,1260,0.36,20377,68,74,0
11,1200,0.46,18872,52,84,0
12,1258,0.38,17520,61,85,0
13,1268,0.29,45879,78,90,1
14,1280,0.30,37137,85,83,1
15,1230,0.36,17721,77,89,0
16,1310,0.25,39504,91,91,1
17,1278,0.24,23115,79,89,1
18,1244,0.67,22301,65,73,0
19,1215,0.38,20722,51,85,0
20,1370,0.18,46918,90,90,1
21,1285,0.35,19418,71,87,0
22,1290,0.48,45460,69,86,1
23,1255,0.25,24718,65,92,0
24,1357,0.30,56766,95,86,1
25,1200,0.61,23358,47,83,0
26,1230,0.47,28851,77,82,1
27,1247,0.54,23591,64,77,0
28,1170,0.49,20192,54,72,0
29,1320,0.33,26668,79,80,0
30,1340,0.17,48123,89,93,1
31,1327,0.24,26730,85,88,1
32,1195,0.57,25271,65,87,0
33,1370,0.18,61921,92,88,1
34,1310,0.24,27487,78,88,0
35,1195,0.60,21853,71,77,1
36,1300,0.45,38937,74,73,1
37,1155,0.56,38597,52,73,1
38,1280,0.41,30882,87,86,1
39,1218,0.37,19365,77,88,1
40,1142,0.43,26859,96,61,1
41,1109,0.32,19684,82,73,1
42,1287,0.43,20179,53,84,0
43,1225,0.54,39883,71,76,1
44,1234,0.29,17998,61,78,0
45,1250,0.49,27879,76,86,0
46,1290,0.35,19948,73,91,0
47,1336,0.28,23772,86,93,0
48,1350,0.19,52468,90,93,1

In [5]:
independent_variables = df.drop('GraduationPercent', axis=1)

x = independent_variables.values
y = df['GraduationPercent'].values

lr = LinearRegression(fit_intercept = True)
lr.fit(x, y)
y_pred = lr.predict(x)

print('Coefficients = ', lr.coef_)

Coefficients =  [ 7.76784666e-02 -2.46379615e+01 -1.64160142e-04 -1.86558406e-01
  1.43632103e+00]

In [6]:
print('Intercept = ', lr.intercept_)

Intercept =  12.591232834644018

In [7]:
print('R^2 = ', lr.score(x, y))

R^2 =  0.5388505927863803

In [8]:
print('Root MSE = ', math.sqrt(metrics.mean_squared_error(y, y_pred)))

Root MSE =  5.00625956147686

In [9]:
x = independent_variables
y = df['GraduationPercent']

x2 = sm.add_constant(x)
ols = sm.OLS(y, x2)
est = ols.fit()

est.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:      GraduationPercent   R-squared:                       0.539
Model:                            OLS   Adj. R-squared:                  0.485
Method:                 Least Squares   F-statistic:                     10.05
Date:                Tue, 25 Mar 2025   Prob (F-statistic):           2.02e-06
Time:                        04:59:52   Log-Likelihood:                -148.45
No. Observations:                  49   AIC:                             308.9
Df Residuals:                      43   BIC:                             320.3
Df Model:                           5
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
const                     12.5912     26.078      0.483      0.632     -40.000      65.183
MedianSAT                  0.0777      0.020      3.856      0.000       0.037       0.118
AcceptanceRate           -24.6380      8.378     -2.941      0.005     -41.534      -7.741
ExpendituresPerStudent    -0.0002   7.98e-05     -2.056      0.046      -0.000   -3.13e-06
Top10PercentHS            -0.1866      0.088     -2.119      0.040      -0.364      -0.009
University                 1.4363      2.236      0.642      0.524      -3.073       5.946
==============================================================================
Omnibus:                        1.261   Durbin-Watson:                   2.001
Prob(Omnibus):                  0.532   Jarque-Bera (JB):                1.113
Skew:                          -0.358   Prob(JB):                        0.573
Kurtosis:                       2.817   Cond. No.                     1.18e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.18e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""